In [1]:
import math

def bed_length_stats(bed_file):
    lengths = []

    with open(bed_file) as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            chrom, start, end, *rest = line.rstrip().split()
            lengths.append(int(end) - int(start))

    n = len(lengths)
    mean = sum(lengths) / n
    variance = sum((x - mean) ** 2 for x in lengths) / n
    std = math.sqrt(variance)

    return n, mean, std


# ---- BED file paths ----
background_n = "/home/maria/Desktop/progetto_inquinanti/risultati_inquinanti/PCB153-vs-CTR/RBP-DEGS/RBPbench/RBP_DEG_specific/intellectual_disability_negative_PSI_PCB153-vs-CTR_ASE_specific_coordinates_enmo/background_sequences.tmp.bed"
background_p = "/home/maria/Desktop/progetto_inquinanti/risultati_inquinanti/PCB153-vs-CTR/RBP-DEGS/RBPbench/RBP_DEG_specific/intellectual_disability_positive_PSI_PCB153-vs-CTR_ASE_specific_coordinates_enmo/background_sequences.tmp.bed"

dase_not_expanded_negative = "/home/maria/Desktop/progetto_inquinanti/risultati_inquinanti/PCB153-vs-CTR/miRNA/negative_PSI/intellectual_disability_negative_PSI_PCB153-vs-CTR_ASE_specific_coordinates.bed"
dase_not_expanded_positive='/home/maria/Desktop/progetto_inquinanti/risultati_inquinanti/PCB153-vs-CTR/miRNA/positive_PSI/intellectual_disability_positive_PSI_PCB153-vs-CTR_ASE_specific_coordinates.bed'


# ---- compute stats ----
n_bg_n, mean_bg_n, std_bg_n = bed_length_stats(background_n)
print("background negatives")
print(f"  intervals: {n_bg_n}")
print(f"  mean length: {mean_bg_n:.2f}")
print(f"  std dev: {std_bg_n:.2f}\n")

# ---- compute stats ----
n_bg_p, mean_bg_p, std_bg_p = bed_length_stats(background_p)
print("background positives")
print(f"  intervals: {n_bg_p}")
print(f"  mean length: {mean_bg_p:.2f}")
print(f"  std dev: {std_bg_p:.2f}\n")

n_da_n, mean_da_n, std_da_n = bed_length_stats(dase_not_expanded_negative)
mean_da_negative_plus_500 = mean_da_n + 500

print("Dase expanded negative")
print(f"  intervals: {n_da_n}")
print(f"  mean length : {mean_da_negative_plus_500:.2f}")
print(f"  std dev: {std_da_n:.2f}\n")

n_da_p, mean_da_p, std_da_p = bed_length_stats(dase_not_expanded_positive)
mean_da_positive_plus_500 = mean_da_p + 500

print("Dase expanded positive")
print(f"  intervals: {n_da_p}")
print(f"  mean length : {mean_da_positive_plus_500:.2f}")
print(f"  std dev: {std_da_p:.2f}\n")

background negatives
  intervals: 5016
  mean length: 818.32
  std dev: 349.46

background positives
  intervals: 5016
  mean length: 771.42
  std dev: 540.11

Dase expanded negative
  intervals: 19
  mean length : 818.32
  std dev: 349.46

Dase expanded positive
  intervals: 19
  mean length : 771.42
  std dev: 540.11

In [2]:
!ls

1-RBPBench.ipynb
1-RBPBench-rbp-deg-specific.ipynb
2-parse_rbpbench_output_positive-negative-psi-deg_specific.ipynb
2-parse_rbpbench_output_positive-negative-psi.ipynb
3-parse_rbp_output-deg_specific.ipynb
3-parse_rbp_output.ipynb
4-rbp-plot-deg-specific.ipynb
enriched_motif_DASE_negative_psi_intellectual_disability.csv
enriched_motif_DASE_positive_psi_intellectual_disability.csv
final_motif_with_position.xlsx
intellectual_disability_PCB153-vs-CTR_ASE_specific_coordinates_enmo
intellectual_disability_PCB153-vs-CTR_ASE_specific_coordinates_search
PCB153-vs-CTR_ASE_specific_coordinates_enmo
PCB153-vs-CTR_ASE_specific_coordinates_search
RBP_BENCH_negative_PSI
RBP_BENCH_positive_PSI
RBP_DEG_specific
RBP_DEG_specific_enriched_motif_DASE_negative_psi_intellectual_disability.csv
RBP_DEG_specific_enriched_motif_DASE_positive_psi_intellectual_disability.csv
RBP_DEG_specific_final_motif_with_position.xlsx

In [3]:
import pandas as pd

# Read the two dataframes
df_pos = pd.read_csv("RBP_DEG_specific_enriched_motif_DASE_positive_psi_intellectual_disability.csv")
df_neg = pd.read_csv("RBP_DEG_specific_enriched_motif_DASE_negative_psi_intellectual_disability.csv")

# Find common columns
common_cols = df_pos.columns.intersection(df_neg.columns)

# Subset to common columns
df_pos_common = df_pos[common_cols]
df_neg_common = df_neg[common_cols]

# Concatenate
df_combined = pd.concat([df_pos_common, df_neg_common], ignore_index=True)
# Remove unwanted columns if they exist
df_combined = df_combined.drop(columns=["IncLevel1", "IncLevel2"], errors="ignore")

# Optional: save to file
# df_combined.to_csv("enriched_motif_DASE_combined.csv", index=False)
df_combined.head()

,rbp_id,motif_id,expanded_sequence,gen_s,gen_e,region_s,region_e,region_len,uniq_count,DASE_sequence,Class,GeneID,geneSymbol,FDR,IncLevelDifference,DE-NOVO
0,CELF2,CELF2_1,chr1:75728150-75728738(+),75728490,75728496,340,346,588,2,chr1:75728150-75728738(+),MXE,ENSG00000117054,ACADM,0.012140,0.229,False
1,CELF2,CELF2_1,chr1:75728150-75728738(+),75728539,75728545,389,395,588,2,chr1:75728150-75728738(+),MXE,ENSG00000117054,ACADM,0.012140,0.229,False
2,CELF2,CELF2_1,chr11:68179881-68180450(-),68180060,68180066,385,391,569,2,chr11:68179881-68180450(-),MXE,ENSG00000110066,KMT5B,0.008150,0.127,False
3,CELF2,CELF2_1,chr11:68179609-68180450(-),68180060,68180066,385,391,841,2,chr11:68179609-68180450(-),MXE,ENSG00000110066,KMT5B,0.003254,0.217,True
4,CELF2,CELF2_1,chr8:74351071-74351716(+),74351081,74351087,10,16,645,1,chr8:74351071-74351716(+),A5SS,ENSG00000104381,GDAP1,0.000716,0.375,False

In [4]:
import pandas as pd
import re

def determine_motif_position_strand(row):
    # Use regex to extract coordinates and strand
    match = re.match(r'(.+):(\d+)-(\d+)\((\+|\-)\)', row['expanded_sequence'])
    if not match:
        # If format is unexpected, mark as unknown
        return 'unknown'
    
    chrom, seq_start, seq_end, strand = match.groups()
    seq_start = int(seq_start)
    seq_end = int(seq_end)
    gen_s = int(row['gen_s'])
    gen_e = int(row['gen_e'])

    # Define upstream/downstream regions based on strand
    if strand == '+':
        upstream_start = seq_start
        upstream_end = seq_start + 250
        downstream_start = seq_end - 250
        downstream_end = seq_end
    else:  # strand == '-'
        upstream_start = seq_end - 250
        upstream_end = seq_end
        downstream_start = seq_start
        downstream_end = seq_start + 250

    # Check if gen_s-gen_e falls in upstream/downstream
    if gen_e <= upstream_end and gen_s >= upstream_start:
        return 'upstream'
    elif gen_s >= downstream_start and gen_e <= downstream_end:
        return 'downstream'
    else:
        return 'exon'

# Apply to dataframe
df_combined['motif_position'] = df_combined.apply(determine_motif_position_strand, axis=1)

In [5]:
df_combined.motif_position.value_counts()

motif_position
exon          43
downstream    35
upstream      22
Name: count, dtype: int64

In [6]:
# Correct way to write to Excel
output_file = "RBP_DEG_specific_final_motif_with_position.xlsx"
df_combined.to_excel(output_file, index=False)

print(f"DataFrame saved to {output_file}")

DataFrame saved to RBP_DEG_specific_final_motif_with_position.xlsx

In [7]:
df_combined

,rbp_id,motif_id,expanded_sequence,gen_s,gen_e,region_s,region_e,region_len,uniq_count,DASE_sequence,Class,GeneID,geneSymbol,FDR,IncLevelDifference,DE-NOVO,motif_position
0,CELF2,CELF2_1,chr1:75728150-75728738(+),75728490,75728496,340,346,588,2,chr1:75728150-75728738(+),MXE,ENSG00000117054,ACADM,0.012140,0.229,False,downstream
1,CELF2,CELF2_1,chr1:75728150-75728738(+),75728539,75728545,389,395,588,2,chr1:75728150-75728738(+),MXE,ENSG00000117054,ACADM,0.012140,0.229,False,downstream
2,CELF2,CELF2_1,chr11:68179881-68180450(-),68180060,68180066,385,391,569,2,chr11:68179881-68180450(-),MXE,ENSG00000110066,KMT5B,0.008150,0.127,False,downstream
3,CELF2,CELF2_1,chr11:68179609-68180450(-),68180060,68180066,385,391,841,2,chr11:68179609-68180450(-),MXE,ENSG00000110066,KMT5B,0.003254,0.217,True,exon
4,CELF2,CELF2_1,chr8:74351071-74351716(+),74351081,74351087,10,16,645,1,chr8:74351071-74351716(+),A5SS,ENSG00000104381,GDAP1,0.000716,0.375,False,upstream
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,RBM22,RBM22_1,chr11:68179219-68179866(-),68179455,68179464,403,412,647,4,chr11:68179219-68179866(-),SE,ENSG00000110066,KMT5B,0.016420,-0.121,False,downstream
96,RBM22,RBM22_1,chr11:68179219-68180080(-),68179461,68179470,611,620,861,4,chr11:68179219-68180080(-),SE,ENSG00000110066,KMT5B,0.016420,-0.121,False,exon
97,RBM22,RBM22_1,chr11:68179219-68180080(-),68179455,68179464,617,626,861,4,chr11:68179219-68180080(-),SE,ENSG00000110066,KMT5B,0.016420,-0.121,False,downstream
98,RBM22,RBM22_1,chr10:125797814-125798395(-),125797987,125797996,400,409,581,1,chr10:125797814-125798395(-),SE,ENSG00000188690,UROS,0.008196,-0.203,False,downstream
99,RBM22,RBM22_1,chr18:79986351-79987000(-),79986672,79986681,320,329,649,1,chr18:79986351-79987000(-),SE,ENSG00000141759,TXNL4A,0.009903,-0.178,False,exon